name: terraform-tests
on: [push]
defaults:
  run:
    working-directory: ./environments/development
jobs:
  terraform-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.2
      - run: terraform fmt
      - run: terraform init
      - run: terraform validate
  tfsec:
    runs-on: ubuntu-latest
    steps:
      - name: tfsec
        uses: tfsec/tfsec-sarif-action@v0.0.3
        with:
          sarif_file: tfsec.sarif