name: terraform-tests
on: [push]
jobs:
  terraform-format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.2
      - run: cd environments/development
      - run: terraform fmt
      - run: terraform init
      - run: terraform validate